workflows:
  android-workflow:
    name: Android Onsen App Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.example.onsenapp"
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
